from pathlib import Path

import platformdirs

APP_NAME = "ytmusic-tui"
DB_NAME = "ytmusic.db"
DEVELOPER = "arandomdev"

DEFAULT_USERNAME = "local"
DEFAULT_VOLUME = 80
MAX_VOLUME = 100
DEFAULT_SEARCH_LIMIT = 10
MIN_SEARCH_LIMIT = 5
MAX_SEARCH_LIMIT = 25
DEFAULT_SUGGEST_LIMIT = 8
MIN_SUGGEST_CHARS = 2
SUGGEST_DEBOUNCE_SECONDS = 0.25
WIDE_LAYOUT_COLUMNS = 110
COMPACT_HEIGHT_ROWS = 24
PLAYBACK_STALL_TICKS = 15
LOG_ENV = "YTMUSIC_LOG"
LOG_FILE_ENV = "YTMUSIC_LOG_FILE"
LOG_LEVEL_ENV = "YTMUSIC_LOG_LEVEL"

APP_DIR = Path(platformdirs.user_data_dir(APP_NAME, DEVELOPER))
DB_PATH = APP_DIR.joinpath(DB_NAME)
