"""Protocol ports for playback, music source, and persistence adapters."""

from typing import Protocol, runtime_checkable

from ytmusic_cli.music.types import AudioStream, Playlist, Song, User, UserSettings


@runtime_checkable
class AudioPlayerProtocol(Protocol):
    def play(self, stream: AudioStream) -> None: ...

    def pause(self) -> None: ...

    def stop(self) -> None: ...

    def is_playing(self) -> bool: ...

    def set_volume(self, volume: int) -> None: ...

    def get_volume(self) -> int: ...

    def get_position(self) -> float: ...

    def has_ended(self) -> bool: ...

    def has_failed(self) -> bool: ...


@runtime_checkable
class MusicSourceProtocol(Protocol):
    def search(self, query: str, max_results: int = 10) -> list[Song]: ...

    def get_stream(self, video_id: str) -> AudioStream: ...


@runtime_checkable
class UserRepositoryProtocol(Protocol):
    def list_users(self) -> list[User]: ...

    def create_user(self, username: str) -> User: ...

    def get_user(self, user_id: int) -> User | None: ...

    def get_by_username(self, username: str) -> User | None: ...

    def delete_user(self, user_id: int) -> None: ...

    def update_settings(self, user_id: int, settings: UserSettings) -> User: ...


@runtime_checkable
class SongRepositoryProtocol(Protocol):
    def upsert(self, song: Song) -> Song: ...

    def get_by_video_id(self, video_id: str) -> Song | None: ...


@runtime_checkable
class PlaylistRepositoryProtocol(Protocol):
    def list_for_user(self, user_id: int) -> list[Playlist]: ...

    def create(self, user_id: int, name: str) -> Playlist: ...

    def get(self, playlist_id: int) -> Playlist | None: ...

    def add_song(self, playlist_id: int, song: Song) -> None: ...

    def remove_song(self, playlist_id: int, video_id: str) -> None: ...

    def delete(self, playlist_id: int) -> None: ...
